"""Build the public website using Python's standard library only."""
import json,html,re,math,pathlib,shutil
ROOT=pathlib.Path(__file__).parent
OUT=ROOT/'_site';OUT.mkdir(exist_ok=True)
D=json.loads((ROOT/'content.json').read_text())
BASE='https://lourdesmarcano.github.io/'
def e(x):return html.escape(str(x),quote=True)
ART_NUMBER=0
def art(theme,seed=0):
    global ART_NUMBER
    ART_NUMBER+=1
    gradient='oxide-'+str(ART_NUMBER)
    # Original conceptual drawings. No measured data or publisher figures.
    ink='#202e37';rust='#a54c32';muted='#9ca9a9';p=[]
    if theme in ('chain','protein'):
        p.append('<path d="M-20 155 Q110 48 245 136 T510 85" fill="none" stroke="#bac5c1" stroke-width="1"/>')
        for i in range(7):
            x=58+i*56;y=123+math.sin(i*.8+seed*.2)*30
            if theme=='protein':
                p.append(f'<circle cx="{x}" cy="{y}" r="27" fill="none" stroke="{muted}" stroke-width="1" stroke-dasharray="2 5"/>')
            p.append(f'<path d="M{x-16} {y-10} l18 -10 19 10 -3 23 -20 7 -14 -12 Z" fill="url(#oxide)" stroke="{rust}" stroke-width=".7"/>')
            p.append(f'<path d="M{x-16} {y-10} l17 11 20 -11 M{x+1} {y+1} l-3 28" fill="none" stroke="#edb89e" stroke-width=".7"/>')
            if theme=='chain':p.append(f'<path d="M{x-8} {y} h19 l-5 -4 m5 4 -5 4" stroke="{ink}" fill="none" stroke-width="1"/>')
    elif theme in ('crystal','heat','light'):
        for i,(x,y,r) in enumerate([(175,120,55),(275,104,38),(316,160,28)]):
            p.append(f'<path d="M{x-r} {y-r*.4} l{r*.85} {-r*.65} {r*1.05} {r*.55} {-r*.08} {r*1.18} {-r*1.05} {r*.4} {-r*.77} {-r*.77} Z" fill="url(#oxide)" stroke="{rust}" stroke-width=".7"/>')
            p.append(f'<path d="M{x-r} {y-r*.4} L{x} {y} L{x+r*.9} {y-r*.5} M{x} {y} v{r*1.04}" fill="none" stroke="#efbba2" stroke-width="1"/>')
        if theme in ('heat','light'):
            for i in range(4):
                x=70+i*25
                p.append(f'<path d="M{x} 210 q-18 -20 0 -40 t0 -40" fill="none" stroke="{rust}" stroke-opacity=".6"/>')
            p.append(f'<path d="M355 24 L290 90 M365 43 L311 99 M340 18 L276 73" stroke="{ink}" stroke-width="1"/>')
        else:
            for y in range(25,235,30):
                for x in range(25,450,30):p.append(f'<circle cx="{x}" cy="{y}" r="1" fill="{muted}" opacity=".4"/>')
    elif theme=='field':
        for i in range(9):
            y=25+i*25
            p.append(f'<path d="M-10 {y} C135 {y},145 {105+i*5},230 {105+i*5} S330 {y},490 {y}" stroke="{muted}" fill="none" stroke-width="1"/>')
        for i in range(6):
            a=i*math.pi/3;x=235+math.cos(a)*70;y=125+math.sin(a)*70
            p.append(f'<path d="M235 125 L{x-18} {y-14} L{x+18} {y+14} Z" fill="url(#oxide)" opacity=".85"/>')
        p.append('<circle cx="235" cy="125" r="17" fill="#f3eee5" stroke="#a54c32"/>')
    elif theme=='scattering':
        for j in range(7):
            p.append(f'<ellipse cx="235" cy="125" rx="{22+j*25}" ry="{10+j*13}" transform="rotate(-25 235 125)" fill="none" stroke="{rust}" opacity="{1-j*.11}"/>')
        p.append('<path d="M40 125 H430 M235 20 V230" stroke="#b0bbb7" stroke-width=".5"/>')
    else:
        for i in range(7):p.append(f'<ellipse cx="235" cy="125" rx="{25+i*13}" ry="90" transform="rotate({i*25} 235 125)" stroke="{muted}" fill="none" stroke-width=".8"/>')
        p.append('<path d="M190 84 L253 62 294 106 275 158 217 187 172 139 Z" fill="url(#oxide)" opacity=".8"/>')
        p.append('<path d="M172 139 L246 122 294 106 M246 122 L253 62 M246 122 L217 187" stroke="#efbba2" fill="none"/>')
    return ('<svg class="science-art" viewBox="0 0 470 250" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="oxide" x2="1" y2="1"><stop stop-color="#c47750"/><stop offset="1" stop-color="#773c30"/></linearGradient></defs>'+''.join(p)+'</svg>').replace('id="oxide"','id="'+gradient+'"').replace('url(#oxide)','url(#'+gradient+')')
def links():return f'<div class="profile-links"><a href="{e(D["links"]["orcid"])}">ORCID ↗</a><a href="{e(D["links"]["scholar"])}">Google Scholar ↗</a><a href="{e(D["links"]["university"])}">University of Oviedo ↗</a><a href="mailto:{e(D["email"])}">Email ↗</a></div>'
def card(p,i=0):
    authors=', '.join(p['authors']);authors=e(authors).replace('Lourdes Marcano','<strong>Lourdes Marcano</strong>')
    cite=' · '.join(filter(None,[e(p['journal']),str(p['year']),e(p['volume'])+(' ('+e(p['issue'])+')' if p['issue'] else ''),e(p['pages'])]))
    doi=f'<a class="read" href="https://doi.org/{e(p["doi"])}">Read article <span aria-hidden="true">↗</span></a><span class="doi">DOI: {e(p["doi"])}</span>' if p['doi'] else '<span class="accepted">Accepted for publication · DOI forthcoming</span>'
    if p.get('pdf'):doi+=f'<a class="read secondary" href="{e(p["pdf"])}">PDF ↗</a>'
    return f'''<article class="publication" data-selected="{str(p['selected']).lower()}" data-search="{e(p['title']+' '+p['journal']+' '+str(p['year'])+' '+p['doi'])}"><div class="paper-art theme-{e(p['theme'])}">{art(p['theme'],i)}<span>{e(p['kind'])} / {e(p['theme'].replace('chain','bioinspired magnetism').replace('heat','thermal response').replace('field','magnetic fields').replace('protein','biomolecular materials').replace('crystal','structure & magnetism').replace('tomography','advanced imaging').replace('light','light & matter'))}</span></div><div class="paper-body"><p class="journal">{cite}</p><h3>{e(p['title'])}</h3><p class="paper-summary">{e(p['summary'])}</p><details class="authors"><summary>{e(p['authors'][0])} et al. <span>Authors</span></summary><p>{authors}</p></details><div class="paper-links">{doi}</div></div></article>'''
def shell(page,title,desc,body):
    nav=''.join(f'<a href="{file}"'+(' aria-current="page"' if key==page else '')+f'>{label}</a>' for key,file,label in [('home','index.html','Home'),('research','research.html','Research'),('publications','publications.html','Publications'),('projects','projects.html','Projects'),('outreach','outreach.html','Outreach'),('about','about.html','About')])
    path='index.html' if page=='home' else page+'.html'
    schema={'@context':'https://schema.org','@type':'Person','name':D['name'],'url':BASE,'image':BASE+'portrait-large.webp','jobTitle':'Physicist and materials scientist','affiliation':{'@type':'Organization','name':'University of Oviedo'},'sameAs':list(D['links'].values())}
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} | Lourdes Marcano</title><meta name="description" content="{e(desc)}"><meta name="theme-color" content="#f8f6f0"><link rel="canonical" href="{BASE+path}"><meta property="og:type" content="website"><meta property="og:title" content="{e(title)} | Lourdes Marcano"><meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{BASE+path}"><meta property="og:image" content="{BASE}portrait-social.jpg"><meta property="og:image:alt" content="Lourdes Marcano in the laboratory"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"><script src="site.js" defer></script><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="index.html"><span class="monogram">lm<span>·</span></span><span>Lourdes Marcano</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span aria-hidden="true">+</span></button><nav id="navigation" aria-label="Main navigation">{nav}</nav></header><main id="main">{body}</main><footer><div class="footer-top"><p>Let’s explore what<br><em>magnetic materials can do.</em></p><a href="mailto:{e(D['email'])}">{e(D['email'])} ↗</a></div><div class="footer-bottom"><span>© Lourdes Marcano · University of Oviedo</span><span>Original conceptual illustrations · No experimental images</span><a href="https://github.com/lourdesmarcano/lourdesmarcano.github.io">Website source ↗</a></div></footer></body></html>'''
def head(label,title,desc):return f'<section class="page-head"><p class="eyebrow">{label}</p><h1>{title}</h1><p class="intro">{desc}</p></section>'
def write(page,title,desc,body):(OUT/('index.html' if page=='home' else page+'.html')).write_text(shell(page,title,desc,body))
selected=[p for p in D['publications'] if p['selected']]
hero='''<section class="hero"><div class="hero-copy"><p class="eyebrow">Physicist & materials scientist · University of Oviedo</p><h1>Lourdes<br><em>Marcano</em><span class="oxide-dot">.</span></h1><p class="tagline">'''+e(D['tagline'])+'''</p><p class="hero-statement">From nature’s magnetic crystals<br>to materials that respond to light.</p><a class="text-link" href="research.html">Explore the science <span>↗</span></a></div><figure class="portrait"><img src="portrait-large.webp" srcset="portrait-small.webp 600w, portrait-large.webp 1000w" sizes="(max-width: 760px) 100vw, 42vw" width="886" height="1181" alt="Lourdes Marcano at a laboratory bench" fetchpriority="high"><figcaption>Magnetic matter. Biological inspiration. New possibilities.</figcaption></figure><span class="hero-index" aria-hidden="true">01 / Matter · Magnetism · Light</span></section>'''
bio=''.join('<p>'+e(p)+'</p>' for p in D['bio'].split('\n\n'))
home=hero+f'<section class="home-intro section"><div><p class="eyebrow">A scientific perspective</p><h2>Learning from nature.<br><em>Designing beyond it.</em></h2></div><div class="prose">{bio}{links()}</div></section>'
home+='<section class="section research-teaser"><div>'+art('chain')+'</div><div><p class="eyebrow">Research vision</p><h2>Small structures.<br><em>Connected questions.</em></h2><p>How do composition and organisation control magnetic behaviour? How do iron oxides turn light and magnetic fields into heat? And how can that knowledge guide functional materials?</p><a class="text-link" href="research.html">Four connected research directions ↗</a></div></section>'
home+='<section class="section"><div class="section-heading"><div><p class="eyebrow">Selected discoveries</p><h2>Science, <em>in focus.</em></h2></div><a class="text-link" href="publications.html">Explore publications ↗</a></div><div class="paper-grid">'+''.join(card(next(p for p in selected if p['doi']==doi),i) for i,doi in enumerate(['10.1021/acsnano.1c09559','10.1039/d6tc01874b']))+'</div></section>'
home+='<section class="independence section"><p class="eyebrow">An independent line of research</p><h2>From biological model systems<br>to <em>functional magnetic matter.</em></h2><p>Leonardo and MSCA fellowships, seed funding and national projects support a research programme connecting magnetic architecture, advanced characterisation and biomedical function.</p><a class="text-link" href="projects.html">Explore the projects ↗</a></section>'
write('home','Nanomagnetism · Bioinspired Materials · Light–Matter Interactions','Lourdes Marcano is a physicist and materials scientist exploring nanomagnetism, bioinspired magnetic materials and the interactions between iron oxides, light and heat.',home)
research=head('Research / Scientific vision','Understanding matter.<br><em>Controlling its response.</em>','I study how magnetic materials behave when their composition, shape and environment change—and how that knowledge can turn nanoscale structures into useful functions.')
lines=[('01','Bioinspired magnetic nanomaterials','chain','Nature builds magnetic materials with extraordinary precision. Magnetotactic bacteria, magnetosomes and engineered proteins offer both model systems and routes to functional nanostructures.','How do biological processes control magnetic crystal formation—and which principles can we carry into materials design?'),('02','Iron oxides & nanomagnetism','crystal','Magnetite, maghemite and doped ferrites connect local chemistry with collective magnetic behaviour. Shape, interfaces, defects and organisation can be as important as composition.','What determines anisotropy, magnetic order and relaxation at the level of an individual particle and its surroundings?'),('03','Light, heat & theranostics','light','Magnetic and photothermal responses create opportunities for thermal interventions. MRI contrast adds a diagnostic dimension, bringing material design into contact with biomedical questions.','How do microscopic structure, doping and defects govern light-to-heat conversion, energy transport and magnetic heating?'),('04','Advanced characterisation','tomography','Synchrotron X-rays and neutrons reveal structures and magnetic states that conventional measurements cannot resolve. I combine microscopy, spectroscopy and scattering with magnetic measurements.','How can we connect local, element-specific information with the behaviour of a complete magnetic system?')]
research+='<div class="research-lines">'+''.join(f'<section class="research-line"><div class="research-visual">{art(t,i)}<span>{n}</span></div><div><p class="eyebrow">Research direction {n}</p><h2>{title}</h2><p>{text}</p><p class="question">{q}</p></div></section>' for i,(n,title,t,text,q) in enumerate(lines))+'</div><section class="section facility"><p class="eyebrow">A view across scales</p><h2>From a single crystal<br>to <em>its working environment.</em></h2><p>My experience spans more than 30 synchrotron and neutron experiments as proposal coordinator or team member. Facilities include ALBA, BESSY II, Elettra, Diamond, MAX IV, ESRF, ISIS and ILL, using XAS/XMCD, STXM, PEEM and polarised small-angle neutron scattering.</p><a class="text-link" href="publications.html">See the discoveries ↗</a></section>'
write('research','Research & Scientific Vision','Scientific questions connecting bioinspired magnetic materials, iron oxides, light-to-heat conversion, theranostics and advanced synchrotron and neutron characterisation.',research)
pubs=head('Publications','Discoveries,<br><em>not just references.</em>','A selection of work connecting magnetic nanoarchitecture, biological materials, advanced imaging and functional responses. Each card gives the scientific idea alongside the article.')
pubs+='<section class="publication-section"><div class="publication-controls"><div class="filter-buttons" role="group" aria-label="Publication collection"><button data-mode="selected" aria-pressed="true">Selected publications</button><button data-mode="all" aria-pressed="false">All publications</button></div><div><label for="publication-search">Find a publication</label><input id="publication-search" type="search" placeholder="Title, journal, year or DOI"></div></div><p class="selection-note">Selected for their contribution to the research story: biological magnetic architecture, individual-particle characterisation and emerging multifunctional materials.</p><p class="result-count" role="status" aria-live="polite"></p><div class="paper-grid" id="publication-grid">'+''.join(card(p,i) for i,p in enumerate(D['publications']))+'</div><p class="no-results" hidden>No matching publications. Try a different title, journal or year.</p></section>'
write('publications','Publications','Explore selected and complete publications by Lourdes Marcano, with scientific summaries, authors and verified DOI links.',pubs)
proj=head('Research projects / Own competitive funding','Building an<br><em>independent research line.</em>','From biological magnetic platforms to engineered theranostic materials: five competitive projects and individual fellowships supporting my own research. Listed from the most recent funding backwards.')
proj+='<div class="project-list">'
for i,p in enumerate(D['projects']):
 proj+=f'<article class="project"><div class="project-visual">{art(p["theme"],i)}<span class="project-number">0{i+1}</span></div><div class="project-content"><p class="eyebrow">{e(p["period"])}</p><h2>{e(p["acronym"])}</h2><p class="project-title">{e(p["title"])}</p><p class="question">{e(p["question"])}</p><p>{e(p["summary"])}</p><ul class="objectives">'+''.join('<li>'+e(o)+'</li>' for o in p['objectives'])+f'</ul><dl class="project-meta"><div><dt>Role</dt><dd>{e(p["role"])}</dd></div><div><dt>Funding</dt><dd>{e(p["amount"])}</dd></div><div><dt>Programme</dt><dd>{e(p["funder"])}</dd></div><div><dt>Reference</dt><dd>{e(p["reference"])}</dd></div></dl><a class="text-link" href="{e(p["url"])}">Official funding information ↗</a></div></article>'
proj+='</div>'
write('projects','Research Projects & Fellowships','Five own competitive grants and fellowships: Research Consolidation, Nano-TherMAG, ProteNano-MAG, BioMAGterials and Nano-roBIOts. Exact PI and MSCA Fellow roles.',proj)
outreach=head('Outreach / Scientific community','Science grows<br><em>through people.</em>','Sharing scientific questions, creating opportunities and making research feel accessible are part of how I work—not activities at the edge of it.')
outreach+='''<section class="outreach-feature section"><div class="outreach-art">'''+art('chain')+'''<span class="big-number">40<span>approximately</span></span></div><div><p class="eyebrow">Schools & scientific curiosity</p><h2>Opening a door<br><em>to science.</em></h2><p>Since 2022, I have visited approximately 40 schools and colleges across Asturias through the University of Oviedo’s science-communication activities, alongside an activity in León. Conversations about magnetic bacteria and nanomaterials offer a starting point for exploring what scientists do and how research works.</p><p>These activities include Science Week, De Gira con la Ciencia and the International Day of Women and Girls in Science.</p></div></section><div class="community-grid section"><article><p class="eyebrow">Mentoring / 2023 & 2025</p><h2>Inspira STEAM</h2><p>As a mentor in Inspira STEAM, I help young people explore scientific and technological careers and encounter women working in research. Mentoring creates space for questions about science, confidence and belonging.</p></article><article><p class="eyebrow">Public conversations / May 2026</p><h2>Pint of Science</h2><p>I volunteered with the local organising team for Pint of Science in Pola de Siero, held on 18–20 May 2026. Bringing researchers and audiences together outside the university makes scientific discussion part of everyday life.</p></article><article><p class="eyebrow">Scientific community / Since 2023</p><h2>Women in Magnetism</h2><p>I am a member of the IEEE Magnetics Society’s Women in Magnetism Committee. My community activities connect scientific exchange with visibility, mentoring and opportunities for women in magnetism.</p><a class="text-link" href="https://ieeemagnetics.org/membership/community/women-magnetism">Women in Magnetism ↗</a></article><article><p class="eyebrow">Scientific exchange / 2026</p><h2>INTERMAG & workshops</h2><p>I co-organised and co-chaired the Magnetic Nanoparticles symposium at INTERMAG 2026 in Manchester, where I also gave an invited talk. My scientific-community work includes organising research workshops and activities in leadership and scientific communication.</p></article></div><section class="future section"><p class="eyebrow">Coming next / Accepted symposium · June 2027</p><h2>Advanced Characterization Techniques<br><em>for Magnetic Nanoparticles.</em></h2><p>I am an organiser of this accepted symposium at the 23rd International Conference on Magnetism. ICM 2027 will take place in San Juan, Puerto Rico, on 14–18 June 2027.</p></section>'''
write('outreach','Outreach & Scientific Community','School science communication, Inspira STEAM mentoring, Pint of Science and Women in Magnetism, alongside scientific workshops and symposium organisation.',outreach)
about=head('About','A physicist’s questions.<br><em>A materials scientist’s approach.</em>','My research connects biological inspiration with experimental materials physics. The common thread is understanding magnetic matter closely enough to design what it can do.')
about+='<section class="about-story section"><figure><img src="portrait-small.webp" width="600" height="800" loading="lazy" alt="Lourdes Marcano in the laboratory"></figure><div class="prose">'+bio+'''<p>I am a permanent faculty member in the Department of Physics, Applied Physics area, at the University of Oviedo, a position held since November 2025. My work combines research with undergraduate and master’s teaching, supervision and scientific mentoring.</p><p>An Extraordinary Doctoral Award, a Marie Skłodowska-Curie Postdoctoral Fellowship, a Leonardo Fellowship and R3 recognition mark different stages of this trajectory. Competitive funding now supports a research programme centred on magnetic and bioinspired nanomaterials.</p>'''+links()+'</div></section>'
timeline=[('2013','Physics','University of Oviedo · Degree in Physics'),('2014','New materials','Master’s training at UPV/EHU'),('2018','PhD in Materials Science & Technology','UPV/EHU · International mention, cum laude and Extraordinary Doctoral Award'),('2019–2021','Synchrotron science','HZB/BESSY II, Berlin · Postdoctoral research'),('2021–present','University of Oviedo','Research and teaching · Permanent faculty since November 2025'),('2023–2025','MSCA / CIC biomaGUNE','ProteNano-MAG · Protein-based and bioinspired magnetic materials'),('2022–present','Independent research','Leonardo, Comienza, Nano-TherMAG and Research Consolidation funding')]
about+='<section class="section trajectory"><p class="eyebrow">A scientific trajectory / Overlapping research stages</p><h2>Different environments.<br><em>One connected direction.</em></h2><ol class="timeline">'+''.join(f'<li><span>{year}</span><div><h3>{title}</h3><p>{desc}</p></div></li>' for year,title,desc in timeline)+'</ol></section>'
write('about','About','The scientific trajectory of Lourdes Marcano: physics, magnetic biomaterials, synchrotron characterisation and independent research at the University of Oviedo.',about)
write('404','Page not found','Page not found.',head('404','A different direction?','This page could not be found. Explore the research or return to the homepage.')+'<section class="section"><a class="text-link" href="index.html">Back to home ↗</a></section>')
for name in ['style.css','site.js','portrait-small.webp','portrait-large.webp','portrait-social.jpg','favicon.svg']:shutil.copy2(ROOT/name,OUT/name)
(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+BASE+'sitemap.xml\n')
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+BASE+p+'</loc></url>' for p in ['index.html','research.html','publications.html','projects.html','outreach.html','about.html'])+'</urlset>')
(OUT/'.nojekyll').write_text('')
print('Built',len(list(OUT.iterdir())),'public files. No private documents included.')
